"""alteracao no campo nome para 100 chars

Revision ID: dcf1965a3e14
Revises: 68f5efe8748d
Create Date: 2022-09-09 15:57:51.192526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf1965a3e14'
down_revision = '68f5efe8748d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column(
            'nome',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            existing_nullable=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column(
            'nome',
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False
        )
        # ### end Alembic commands ###
